### ISSUE TITLE
Onboarding carlos

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/handbook#5]
## Olá!

Bem vindo a Assessoria de Inteligência de Dados. Complete as seguintes tarefas para se familiarizar com nossa organização:

- [x] Assista esse [vídeo](https://www.youtube.com/watch?v=mDYoTC6fJ8E) para uma [introdução ao github](https://www.youtube.com/watch?v=mDYoTC6fJ8E)
- [ ] Complete as [lições](https://github.com/splor-mg/handbook/blob/main/software-carpentry.md) da Software Carpentry
- [x] Leia o artigo [Potencializando a Fluência em Dados: Estratégias de Gestão do Conhecimento na Administração Pública](https://github.com/splor-mg/consad-2023/blob/main/consad-2023.pdf) que descreve nosso [banco de conhecimento](https://github.com/splor-mg/notas) e a nota [Relacionamento das bases no relatório operacional: método Concatenate x Linktable](https://splor-mg.github.io/notas/main/20231804T160439/). Explore o processo de revisão para a escrita dessa nota via [pull requests](https://github.com/splor-mg/notas/pull/7).
- [x] Assita ao TED Talk [Clay Shirky: Como a internet irá (um dia) transformar o governo](https://www.ted.com/talks/clay_shirky_how_the_internet_will_one_day_transform_government?hasSummary=true&language=pt-br)
- [x] Assista a [apresentação](https://youtu.be/JUW60w1jDdM?t=1346) relâmpago e seção de [dúvidas](https://youtu.be/JUW60w1jDdM?t=3734) na Conferência Brasileira de Jornalismo de Dados e Métodos Digitais (CODA 2021) falando um pouco sobre a importância de documentação de dados legível por máquina e `docs as code`.
- [x] Complete a oficina "Dados abertos sem fricção" ([vídeo](https://www.youtube.com/watch?v=tZ0bmlnqMuY) e [apresentação](https://ead.prodemge.gov.br/pluginfile.php/19736/mod_resource/content/2/Dados%20Abertos%20sem%20friccao-DCTA-CGE.pdf)), ocorrida durante a 3ª Semana INOVA, de 2020. 
- [x] Crie um data package que documente algum conjunto de dados utilizando nosso [cookiecutter](https://splor-mg.github.io/cookiecutter-datapackage/0.1/). Discuta com seu chefe qual conjunto de dados é mais adequado.

**Comment by carloshob** [comment]
> @carloshob ainda acho que faz sentido vc terminar as lições do software carpentry mas pelo prazo não faz mais sentido falar que estamos na etapa de onboarding.
> 
> O estudo continua como parte normal do desenvolvimento.

concordo, @fjuniorr!
