### ISSUE TITLE
estudar biblioteca material mkdocs

### ISSUE THREAD

**Issue by carloshob** [splor-mg/handbook#7]
Objetivo de implementar o site stático do handbook utilizando o mkdocs

Links uteis: 

- [x] [link](https://squidfunk.github.io/mkdocs-material)

**Comment by gabrielbdornas** [comment]
@carloshob, conforme conversamos, acredito que já é possível criar nossa primeira versão do site no repositório. Se tiver alguma dúvida, basta me acionar por aqui.

**Comment by gabrielbdornas** [comment]
@carloshob, acredito que o estudo inicial após #9 foi concluído. Os refinamentos irão ocorrer a mendida que trabalhamos no site.
